S figure10
WayScience/pyroptosis_signature_data_analysis pull request #100
Opened 2024-01-23 22:18 UTC by MikeLippincott

Supplementary Figure S10 - Treatment Holdout for MLP

2024-01-23 22:38 UTC, jenna-tomkinson requested changes
I love this figure so far! 

I only have one concern, which is the PR curve, as they do not look like a typical PR curve and is missing some lines (e.g., shuffled data, etc.). It is also showing one model to be 100% perfect. Please let me know if this is supposed to be expected or not.

Let me know when you want me to review again.

2024-01-23 22:38 UTC, jenna-tomkinson commented on figures/S10_supplemental_figure10/figures/PR_curves.png
Some comments:

1. Looks like `Apoptosis` is missing on this graph, or it is overlapping with either of the other two classes. I would recommend finding a way to show it if possible.
2. I also don't see the `shuffled` lines either.
3. It seems strange that the pyroptosis class is perfect precision across all recall, which I do believe means the model predicts correctly 100% of the time. This smells fishy, as Greg would say haha. I would recommend checking this out.

2024-01-23 22:38 UTC, jenna-tomkinson commented on figures/S10_supplemental_figure10/figures/f1_score.png
Small recommendation:

It might be good to keep the color consistent with the other plots, so I would recommend changing the color of these bars to purple which represents pyroptosis.

2024-01-23 22:38 UTC, jenna-tomkinson commented on figures/S10_supplemental_figure10/figures/S10.png
This is a great figure! I only have one small comment.

Looks like Panel B is overlapping on top of the `Predicted Class` legend in Panel A (cuts off pyroptosis). I recommend fixing this overlap if possible.

2024-01-24 20:33 UTC, MikeLippincott commented on figures/S10_supplemental_figure10/figures/S10.png
removed PR plot

2024-01-24 20:33 UTC, MikeLippincott commented on figures/S10_supplemental_figure10/figures/PR_curves.png
1. removed PR curve
2. removed PR cureve

2024-01-24 20:33 UTC, MikeLippincott commented on figures/S10_supplemental_figure10/figures/f1_score.png
changed colour

2024-01-24 22:17 UTC, jenna-tomkinson approved these changes
A-MAZING :smile:

2024-01-25 00:23 UTC, merged