Nomic nELISA analysis - umap
WayScience/pyroptosis_signature_data_analysis pull request #18
Opened 2023-04-20 21:45 UTC by MikeLippincott

2023-04-21 19:16 UTC, jenna-tomkinson requested changes
The main reason why I am asking for changes is because I noticed that your UMAP figures that were meant to be specific to the cell type are the exact same (containing both cell type clusters). Since you were planning to have individual UMAPs for each cell type, you will need to go back and rerun to correct this.

I have provided other comments as well, so please let me know if you have any questions!

2023-04-21 19:16 UTC, jenna-tomkinson commented on Nomic_Analysis/Data/README.md
Consider adding information about the process you are taking to clean the data, why the data needs to be clean, provide screenshot examples, etc.

2023-04-21 19:16 UTC, jenna-tomkinson commented on Nomic_Analysis/Data/nbconverted/clean_data.py
> +#!/usr/bin/env python
Like with the README comment, consider adding a small description with the point of this notebook and why you are cleaning the data (e.g. wanting to reproduce their results, etc.).

2023-04-21 19:16 UTC, jenna-tomkinson commented on Nomic_Analysis/Data/nbconverted/clean_data.py
> +for i in MetaData["position"].astype(str):
I really like this! (much better than manually doing like I have done)

2023-04-21 19:16 UTC, jenna-tomkinson commented on Nomic_Analysis/README.md
> +# Nomic nELISA panel analysis
Based on this README, maybe you can remove that README from the `Data` folder so you can have all of the cleaning information here.

2023-04-24 15:45 UTC, MikeLippincott commented on 0.Exploratory_Data_Analysis/Exploratory_Data_Analysis.ipynb
> +   "version": "3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]"
I do not know why that is....hmmm let me do some investigating. Might be a hiccup

2023-04-24 15:51 UTC, MikeLippincott commented on Nomic_Analysis/0.umap/PBMC/nbconverted/PBMC_umap_Visualization.py
> +        title="UMAP projection of the nELISA data",
Good Idea, this will add clarity. Thank you!

2023-04-24 16:12 UTC, MikeLippincott commented on Nomic_Analysis/0.umap/PBMC/nbconverted/PBMC_umap_Visualization.py
> +col_list = [
I am going to reject this change for the sake of keeping the notebook simple

2023-04-24 16:13 UTC, MikeLippincott commented on Nomic_Analysis/0.umap/PBMC/nbconverted/PBMC_umap_Visualization.py
> +    save_name : str
yes, I changed it to pathlib.Path

2023-04-24 16:14 UTC, MikeLippincott commented on Nomic_Analysis/0.umap/PBMC/nbconverted/PBMC_umap_Visualization.py
> +    umap_graph(
implemented

2023-04-24 16:21 UTC, MikeLippincott commented on Nomic_Analysis/0.umap/README.md
> +each cell line has the same analysis but has been assigned their own folder.
Updated the README.md

2023-04-24 16:27 UTC, MikeLippincott commented on Nomic_Analysis/0.umap/SH-SY5Y/nbconverted/PBMC_umap.py
> +#!/usr/bin/env python
caught the error as well post PR open. Changing

2023-04-25 18:58 UTC, jenna-tomkinson approved these changes
LGTM!

I added one comment where there is a typo in one of your file names. Thank you for addressing the majority of my comments!

The figures are looking amazing and I am excited for further analysis and the MLP!

2023-04-27 04:13 UTC, MikeLippincott commented on Nomic_Analysis/Data/raw/Analyte_Data_UCA1_2023.04.11.csv
this is the raw file that nomic sent. The analyte is the protein being detected in the ELISA

2023-04-27 04:14 UTC, merged