MLP Hyperparameter Optimization Binary Clasification Model
WayScience/pyroptosis_signature_data_analysis pull request #4
Opened 2023-03-15 04:06 UTC by MikeLippincott

This PR contains code that does few things:

Does Hyperparameter optimization on a binary classification MLP where the goal is to predict if a cell was either treated with pyroptotic inducing agents or not based on features.

From the optimized hyperparameters, create the MLP, train the MLP, and test the MLP.

note: I opted against placing functions in this notebook in a helper file as these functions define the workflow and the model architecture.

2023-03-15 17:58 UTC, axiomcura commented
Very neat Notebook! However, one general comment. 

You have created lots of functions in your analysis, but they are quite large! I would suggest adding some doc-string documentation to your function to make it easier to read what you're doing! 

Overall good PR!

2023-03-15 18:53 UTC, d33bs requested changes
Nice work! I have comments here and also from ReviewNB which are forthcoming (will post after the Github comments). Please don't hesitate to let me know if you have any questions. 

I'd request changes on removing the `pyc` files from this PR before approval. All other comments and suggestions are flexible to what you think is best.

2023-03-16 14:23 UTC, MikeLippincott commented
<p>Documentation added, this is a global variable for use in later functions (optimization function and model training function). </p><p> </p><p>An alternative is to make each of these functions methods in a class and have constants in the init method so that it is accessible. Thoughts?</p><p> </p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470602909'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 14:30 UTC, MikeLippincott commented
<p>I had not thought of this, thank you. Changes have been made, easy change.</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470499400'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 14:39 UTC, MikeLippincott commented
<p>Constructed class docstring, thank you for pointing this out. Documentation of functions, and classes is something that I need to work on throughout this file.</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470602983'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 14:39 UTC, MikeLippincott commented
<p>At some point during testing yes, but I don't think this needs to be present anymore. I am removing it.</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470499445'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 14:47 UTC, MikeLippincott commented
<p>I am seeing a theme of improving documentation. This is something that I am taking into account for future code. Thank you :)</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603033'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 14:47 UTC, MikeLippincott commented
<p>Documentation added.</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603033'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 14:48 UTC, MikeLippincott commented
<p>added spelling fix!</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603064'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 15:46 UTC, MikeLippincott commented
<p>Added a docstring</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603126'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 16:07 UTC, MikeLippincott commented
<p> I think so, this is something I will be working on in a later PR. I want to place functions in a class and reuse functions. I think this is a big refactor for this PR though.</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603154'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 16:08 UTC, MikeLippincott commented
<p>Added Documentation</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470499466'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 17:37 UTC, MikeLippincott commented
<p>doc string added</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603218'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 17:53 UTC, MikeLippincott commented on 1.Machine_Learning_MLP/Hyperparameter_Optimization.ipynb
There was supposed to be but my per-commit was raising issues and would not allow me to push the converted file so I removed it now that we have ReviewNB

2023-03-16 21:20 UTC, d33bs commented
<p>Sounds good!</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603261'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 21:21 UTC, d33bs commented
<p>👍</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603188'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 21:21 UTC, d33bs commented
<p>I understand, sounds good!</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470603154'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 21:22 UTC, d33bs commented
<p>👍</p>

---

 <a href='https://app.reviewnb.com/WayScience/pyroptosis_signature_data_analysis/pull/4/discussion/#comment-1470602983'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-03-16 21:24 UTC, d33bs commented on 1.Machine_Learning_MLP/Hyperparameter_Optimization.ipynb
Sounds good!

2023-03-16 21:24 UTC, d33bs approved these changes

2023-03-16 21:52 UTC, merged