Figure4
WayScience/pyroptosis_signature_data_analysis pull request #89
Opened 2024-01-14 06:20 UTC by MikeLippincott

Figure 4 updates

2024-01-18 18:33 UTC, jenna-tomkinson requested changes
Figure 4 is looking awesome! I left some comments to address so please let me know if you have any questions. I would be happy to rereview whenever!

I had one question, why do some figures have an SVG saved and other don't. Just curious!

2024-01-22 15:50 UTC, MikeLippincott commented on figures/4.figure4/figures/regression/PBMC/aggregated_with_nomic/local_variance_r2.png
Yes, different plots and I am not too concerned about individual plots and more concerned about the patchwork plots

2024-01-22 15:50 UTC, MikeLippincott commented on figures/4.figure4/figures/regression/PBMC/aggregated_with_nomic/global_variance_r2.png
I am ignoring these in this notebook

2024-01-22 15:50 UTC, MikeLippincott commented on figures/4.figure4/figures/regression/PBMC/aggregated_with_nomic/global_prediction_trend.png
I am not using global prediction in this notebook but rather the supplemental figure

2024-01-22 17:23 UTC, jenna-tomkinson approved these changes
This figure looks great! I only made two small comments for you to address prior to merging, but I think it is ready to go! Good job!

2024-01-22 17:23 UTC, jenna-tomkinson commented on figures/4.figure4/figures/figure4.png
Looks like you have two of this same figure, one in this location and the other under `figures/4.figure4/figures/regression/PBMC/figure4.png`.

I would recommend only including one of this figure unless there is a specific reason.

2024-01-22 17:23 UTC, jenna-tomkinson commented on figures/4.figure4/figures/regression/PBMC/figure4.png
After in-person discussion, my last recommendation is to change the name `Compartment` to `Object` to hopefully avoid the overlapping with the heatmap. The term `Object` is used within the CellProfiler manual and CellProfiler community so it would make sense to use it, though `Compartment` might be easier to understand for biologists.

Other than that, 10/10 figure! :tada:

2024-01-23 02:27 UTC, MikeLippincott commented on figures/4.figure4/figures/figure4.png
removed the second copy

2024-01-23 02:29 UTC, merged